M48
; DRILL file {KiCad (6.0.10-0)} date 2023 January 28, Saturday 16:51:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-28T16:51:06+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X304.2Y-170.495
X304.2Y-175.495
T2
X88.75Y-204.25
X291.1Y-221.2
X303.0Y-82.0
T3
X281.4Y-123.75
X303.6Y-110.5
X303.6Y-138.5
T4
X89.0Y-78.015
X90.0Y-217.929
X299.0Y-78.015
X300.0Y-217.929
T0
M30
