on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: ['12.2.Rel1', 'latest']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GNU Arm Embedded Toolchain - ${{ matrix.gcc }}
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: ${{ matrix.gcc }}
      - run: arm-none-eabi-gcc --version

      #steps:
      #- name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      #  uses: carlosperate/arm-none-eabi-gcc-action@v1
      #  with:
      #    release: '12.2.Rel1' # <-- The compiler release to use
      
      - name: Build ARM executable
        run: make
      
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: upload ARM artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/LivSynth.elf
          asset_name: LivSynth.elf
          asset_content_type: application/octet-stream
      
      #- name: Release
      #  if: startsWith(github.ref, 'refs/tags/')
      #  uses: JamesIves/github-pages-deploy-action@v4.3.3
      #  with:
      #    branch: gh-pages
      #    folder: path to page files
      #    target-folder: _pages/<path>