on:
  push:
    #branches: [ "main" ]
    branches-ignore:
      - 'dev*'
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: ['latest']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GNU Arm Embedded Toolchain - ${{ matrix.gcc }}
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: ${{ matrix.gcc }}
      - run: arm-none-eabi-gcc --version
      
      - name: Build ARM executable
        run: make
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: |
            ./build/LivSynth.elf
            ./build/LivSynth.hex
            ./build/LivSynth.map
            ./build/LivSynth.bin
      
      #- name: Release
      #  if: startsWith(github.ref, 'refs/tags/')
      #  uses: JamesIves/github-pages-deploy-action@v4.3.3
      #  with:
      #    branch: gh-pages
      #    folder: path to page files
      #    target-folder: _pages/<path>